{{- if and .Values.monitor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-monitor.rollbackFullname" . }}
  labels: {{- include "cf-monitor.labels" . | nindent 4 }}
  {{- with .Values.monitor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
