apiVersion: v1
kind: ServiceAccount
metadata:
  {{- /* has to be a constant */}}
  name: codefresh-engine
  labels: {{- include "cf-re.labels" . | nindent 4 }}
  {{- with .Values.re.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
