apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-vp.fullname" . }}
  labels: {{- include "cf-vp.provisionerLabels" . | nindent 4 }}
  {{- with .Values.volumeProvisioner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}